pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/AbdullaAlAzim/localbet-cypress.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        
        stage('Run Cypress Tests') {
            steps {
                script {
                    sh 'npx cypress run'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Tests completed!'
        }
    }
}
